/**
 * Vite Plugin: Defer CSS Loading
 *
 * This plugin transforms CSS link tags to defer their loading,
 * preventing them from blocking the initial render while still
 * loading them as quickly as possible.
 *
 * Technique: Uses media query trick to load CSS non-blocking
 * - Initially loads with media="print" (non-blocking)
 * - Swaps to media="all" after load via onload handler
 */

import type { Plugin } from 'vite';

export function deferCssPlugin(): Plugin {
  return {
    name: 'defer-css',
    enforce: 'post',
    transformIndexHtml(html) {
      // Find CSS link tags generated by Vite
      // Pattern: <link rel="stylesheet" crossorigin href="/assets/css/index-[hash].css">
      const cssLinkRegex = /<link\s+rel="stylesheet"\s+crossorigin\s+href="(\/assets\/css\/[^"]+\.css)"\s*>/g;

      // Transform CSS links to defer loading
      html = html.replace(cssLinkRegex, (match, href) => {
        return `<!-- Preload CSS for faster loading -->
    <link rel="preload" href="${href}" as="style">
    <!-- Load CSS non-blocking with media query trick -->
    <link rel="stylesheet" href="${href}" media="print" onload="this.media='all'; this.onload=null;">
    <!-- Fallback for browsers without JavaScript -->
    <noscript><link rel="stylesheet" href="${href}"></noscript>`;
      });

      return html;
    },
  };
}
